version: "3"
services:
  threads:
    build: 
      context: threads-service
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@host.docker.internal:8432/postgres 
    ports: ['8001:8001']
  posts:
    build: 
      context: posts-service
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@host.docker.internal:7432/postgres 
    ports: ['8002:8002']
  child-metadata:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  child:
    image: hasura/graphql-engine:v2.33.0.cli-migrations-v3
    ports: ['8003:8080']
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@child-metadata:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    volumes:
      - ./child-graph/metadata:/hasura-metadata
  parent-metadata:
    image: postgres:15
    restart: always
    volumes:
      - db1_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  parent:
    image: hasura/graphql-engine:v2.33.0.cli-migrations-v3
    ports: ['8080:8080']
    restart: always
    depends_on: 
      - child
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@parent-metadata:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    volumes:
      - ./parent-graph/metadata:/hasura-metadata
      - ./parent-graph/config.yaml:/hasura-metadata/config.yaml

volumes:
  db_data:
  db1_data:

 
